Just added some CLI arguments
ValdikSS/tor-relay-scanner pull request #1
Opened 2022-03-05 18:19 UTC by gp2112

Hi!
I Just have added command options to allow the user define easily the number of random relays to test and the number of relays to scan (or until the end, if it's the case).

2022-03-06 18:39 UTC, ValdikSS requested changes

2022-03-06 18:39 UTC, ValdikSS commented on src/tor_relay_scanner/scanner.py
>  TIMEOUT = 10.0
Please remove this timeout, it's useless now

2022-03-06 18:39 UTC, ValdikSS commented on src/tor_relay_scanner/scanner.py
> +    parser.add_argument('--timeout', type=float, nargs='?', default=10.0)
Please write a text description for this option

2022-03-06 18:51 UTC, ValdikSS commented on src/tor_relay_scanner/scanner.py
> +    parser.add_argument('--timeout', type=float, nargs='?', default=10.0)
num_relays → The number of concurrent relays tested
working_relay_num_goal → Test until at least this number of working relays are found
timeout → socket connection timeout

2022-03-07 14:21 UTC, gp2112 commented
@ValdikSS I've added the descriptions you had asked and removed TIMEOUT constant.

2022-03-07 14:23 UTC, gp2112 commented on src/tor_relay_scanner/scanner.py
> +    def __init__(self, timeout=10.0):
just created the constructor to allow the timeout setting

2022-03-07 19:51 UTC, merged

2022-03-07 19:51 UTC, ValdikSS commented
Looks great, thanks, merged!